name: SpectreCounter
options:
  bundleIdPrefix: com.spectre
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  projectFormat: "12"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_FILE: SpectreCounter/Info.plist

packages:
  CoreXLSX:
    url: https://github.com/CoreOffice/CoreXLSX
    from: "0.14.0"

targets:
  SpectreCounter:
    type: application
    platform: iOS
    sources:
      - path: SpectreCounter
        excludes:
          - "**/.DS_Store"
          - "Resources/**"
    resources:
      - path: SpectreCounter/Resources/Assets.xcassets
    dependencies:
      - package: CoreXLSX
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.spectre.counter
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: SpectreCounter/Info.plist
      properties:
        CFBundleDisplayName: Spectre Counter
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        LSSupportsOpeningDocumentsInPlace: true
        UIFileSharingEnabled: true
        UISupportsDocumentBrowser: true
