import SwiftUI

/// Sheet for adding a new zone in AR placement mode
struct AddARZoneSheet: View {
    let site: ZCSite
    let parent: ZCZone?
    let arCoordinator: ARZoneCoordinator

    @Environment(\.dismiss) private var dismiss

    @State private var name = ""
    @State private var code = ""
    @State private var selectedType: ZoneType = .other
    @State private var blobRadius: Float = 0.15
    @State private var selectedColor: Color = .blue

    var body: some View {
        NavigationStack {
            Form {
                // Zone info section
                Section("Zone Info") {
                    TextField("Name", text: $name)
                        .textContentType(.name)

                    TextField("Code (e.g., WIC-01)", text: $code)
                        .textInputAutocapitalization(.characters)
                        .onChange(of: name) { _, newValue in
                            if code.isEmpty {
                                suggestCode(for: newValue)
                            }
                        }

                    Picker("Type", selection: $selectedType) {
                        ForEach(ZoneType.allCases) { type in
                            Label(type.displayName, systemImage: type.icon)
                                .tag(type)
                        }
                    }
                    .onChange(of: selectedType) { _, newType in
                        selectedColor = Color(newType.iconColor)
                        if code.isEmpty || isAutoGeneratedCode(code) {
                            suggestCode(for: name)
                        }
                    }
                }

                // Parent zone info
                if let parent = parent {
                    Section("Parent Zone") {
                        HStack {
                            Image(systemName: parent.zoneType.icon)
                                .foregroundColor(parent.zoneType.iconColor)
                            Text(parent.name)
                            Spacer()
                            Text(parent.code)
                                .foregroundColor(.secondary)
                        }
                    }
                }

                // AR appearance section
                Section("AR Appearance") {
                    VStack(alignment: .leading) {
                        Text("Blob Size")
                            .font(.caption)
                            .foregroundColor(.secondary)

                        HStack {
                            Text("Small")
                                .font(.caption2)
                            Slider(value: $blobRadius, in: 0.05...0.3)
                            Text("Large")
                                .font(.caption2)
                        }
                    }

                    ColorPicker("Blob Color", selection: $selectedColor)
                }

                // Quick templates
                if parent == nil {
                    Section("Quick Add from Template") {
                        ForEach(ZoneType.allCases.filter { $0 != .other }) { type in
                            Button {
                                applyTemplate(type)
                            } label: {
                                HStack {
                                    Image(systemName: type.icon)
                                        .foregroundColor(type.iconColor)
                                        .frame(width: 24)

                                    Text(type.displayName)
                                        .foregroundColor(.primary)

                                    Spacer()

                                    let templates = Canon.templates(for: type)
                                    Text("\(templates.count) sub-zones")
                                        .font(.caption)
                                        .foregroundColor(.secondary)
                                }
                            }
                        }
                    }
                }
            }
            .navigationTitle(parent == nil ? "Add Zone" : "Add Sub-Zone")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                }

                ToolbarItem(placement: .confirmationAction) {
                    Button("Add") {
                        addZone()
                    }
                    .disabled(name.isEmpty || code.isEmpty)
                }
            }
        }
        .presentationDetents([.medium, .large])
        .onAppear {
            selectedColor = Color(selectedType.iconColor)
        }
    }

    private func suggestCode(for name: String) {
        let prefix = selectedType.codePrefix
        let existingCodes = site.zones.map { $0.code }

        // Find next available number
        var num = 1
        var candidate = "\(prefix)-\(String(format: "%02d", num))"
        while existingCodes.contains(candidate) {
            num += 1
            candidate = "\(prefix)-\(String(format: "%02d", num))"
        }

        code = candidate
    }

    private func isAutoGeneratedCode(_ code: String) -> Bool {
        // Check if code matches pattern like "WIC-01"
        let pattern = "^[A-Z]+-\\d{2}$"
        return code.range(of: pattern, options: .regularExpression) != nil
    }

    private func applyTemplate(_ type: ZoneType) {
        name = type.displayName
        selectedType = type
        selectedColor = Color(type.iconColor)
        suggestCode(for: name)
    }

    private func addZone() {
        guard let position = arCoordinator.pendingPlacementPosition else {
            dismiss()
            return
        }

        arCoordinator.addZone(
            name: name,
            code: code,
            zoneType: selectedType,
            parent: parent,
            position: position
        )

        arCoordinator.pendingPlacementPosition = nil
        dismiss()
    }
}

#Preview {
    AddARZoneSheet(
        site: ZCSite(name: "Test Site"),
        parent: nil,
        arCoordinator: ARZoneCoordinator()
    )
}
